### ISSUE TITLE
Mobile theme

### ISSUE THREAD

**Issue by bpierre** [lesintegristes/lesintegristes-theme#1]

**Comment by gregoiredierendonck** [comment]
What for a responsive website?
http://mobile.smashingmagazine.com/2012/08/22/separate-mobile-responsive-website-presidential-smackdown/

**Comment by kaneel** [comment]
What for an adaptive website? :)

**Comment by bpierre** [comment]
Of course! I proceeded by priority, but if you’re ready for the big jump… :-)

**Comment by bpierre** [comment]
I close this issue, it’s part of the global redesign.
