### ISSUE TITLE
[FR] Nom du blog

### ISSUE THREAD

**Issue by bpierre** [lesintegristes/lesintegristes-theme#19]
J’utilise le nom « Les intégristes » quand je parle du blog, parfois « lesintegristes.net », mais on a aussi « Les Intégristes » sur le blog.

Je me pose tout le temps la question, je pense qu’il nous faut une orthographe « officielle » qui pourra être utilisée partout.

Que préférez-vous ?
1. Les intégristes - :two: votes
2. Les Intégristes - :one: vote
3. lesintegristes.net
4. Autre ?

PS : je passe en français pour ce bug puisque ça n’intéresse que nous. Peut-être qu’il faudrait passer en français sur les autres aussi, pendant la phase de redesign, pour faciliter la communication.

**Comment by ericlebihan** [comment]
Je serais partant pour garder l'orthographe la plus simple. "Les intégristes", intégriste étant un nom commun, c'est ce qui me parait le plus évident.

**Comment by kaneel** [comment]
Il faut aussi integration-francaise.fr :)

**Comment by ericlebihan** [comment]
Oui un truc genre macaron "membre de l'intégration française", avec un coq
? :-)

On Fri, Sep 21, 2012 at 7:35 PM, Guillaume Richard <notifications@github.com

**Comment by kaneel** [comment]
J'en ai reparlé à Benoit, faut qu'on se fasse un meeting intégristes avec lui et qu'on lui donne un cahier des charges

**Comment by gregoiredierendonck** [comment]
Je vote pour:

Les Intégristes.

Pour la "_Marque de Noblesse_"
;)

**Comment by bpierre** [comment]
Les Intégristes a un avantage, on peut dire « sur le blog des Intégristes », ce qui est différent de « sur le blog des intégristes ». :-)
Mais je trouve que le mot est moche avec un I.

Allez, je vote pour « Les intégristes » !

@gafour @grid23 @kReEsTaL un avis ?

**Comment by gregoiredierendonck** [comment]
Ce n'est pas donné à tout le monde d'avoir bon goût. Je respecte.

**Comment by gregoiredierendonck** [comment]
;)

**Comment by bpierre** [comment]
<img src="http://found.pierrebertet.net/cool.gif">

**Comment by ericlebihan** [comment]
Je trouve même que "les intégristes" sans majuscule au "l" (comme sur le site en vrai) ça a de la classe, non ?

Revoir :
1. Le footer : "Thème par Grégoire Dierendonck (design) et Les Intégristes (code). Merci Wordpress, jQuery, PHP et Apache."
2. Le title "Les intégristes"
3. Page auteur : "Les Intégristes est un blog ouvert à tous, n’hésitez pas à nous contacter pour participer à sa rédaction. :)"

Pas très homogène tout ça...

**Comment by bpierre** [comment]
> Je trouve même que "les intégristes" sans majuscule au "l" (comme sur le site en vrai) ça a de la classe, non ?

Pour le logo oui, mais plus aucune distinction à l’écrit.

> Pas très homogène tout ça...

C’était « Les Intégristes » partout au départ. Maintenant il faut mettre à jour le thème ! :-)

**Comment by kReEsTaL** [comment]
Moui, d'accord ! Mention spéciale pour le GIF (et pour le chien).

**Comment by gregoiredierendonck** [comment]
Pareil, je vote pour le GIF (et pour le chien).

**Comment by ericlebihan** [comment]
Ok donc dorénavant on aura le gif avec le chien à la place du logo.

**Comment by kaneel** [comment]
T'aimes les chians ?

ps: Désolé, je devais la faire

2012/9/25 ericlebihan notifications@github.com

> Ok donc dorénavant on aura le gif avec le chien à la place du logo.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lesintegristes/lesintegristes-theme/issues/19#issuecomment-8846526.

## 

// Guillaume *kaneel *Richard http://mynameiskaneel.com
// With many lower than 3

**Comment by bpierre** [comment]
Bon je ne suis pas sûr d’avoir compris l’avis de tout le monde, mais je suis parti sur « Les intégristes » : @2eb8d014b7faaa075300825db8f3e151a32ab3ea

N’hésitez pas à rouvrir ce bug si vous pensez que c’est une mauvaise idée.
