### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by ericlebihan** [lesintegristes/lesintegristes-theme#22]
What about having a Facebook page for more visibility ?

**Comment by kaneel** [comment]
meh-face :/

**Comment by ericlebihan** [comment]
Could you be more specific ? :-)

**Comment by bpierre** [comment]
<img src="http://bukk.it/sad-keanu.jpg">

**Comment by ericlebihan** [comment]
I am asking again : why not ? :-)

https://www.facebook.com/alistapart
https://www.facebook.com/smashmag?ref=ts
https://www.facebook.com/pages/HTeuMeuLeu/161557707215204?ref=ts

Among others...

Keep you mind open, even if you HATE Facebook.

I am waiting to listen to your aguments, dudes.

**Comment by kaneel** [comment]
Thought my point was clear: couldn't care less.
So, I don't have any pros or cons, I just really don't care :(

**Comment by bpierre** [comment]
There are a ton of ethical arguments (closed web, privacy, [THIS](https://twitter.com/chapeaudefee/status/248599349481836544/photo/1)), but the main reason for me is that Facebook sounds like “farmville”, “like” and other poor quality things.

Agree with kaneel too: we don’t care, Facebook belongs to the past :-)

**Comment by ericlebihan** [comment]
OK I see that's a point we can't discuss... Closed issue.

**Comment by bpierre** [comment]
I don't know, maybe I'm a bit extreme, but I will never support Facebook as it is today. Maybe we should ask others?
