### ISSUE TITLE
[FR] Qu’est-ce qu’une Note ?

### ISSUE THREAD

**Issue by bpierre** [lesintegristes/lesintegristes-theme#33]
### Pas de titre / Titre automatique

Les notes n’ont pas de titre, ou plutôt il est définit automatiquement d’après les premiers mots du contenu.
### Contenu limité

Je ne suis pas vraiment pour ce genre de limitation, mais on s’était posé la question la première fois, et on a décidé que c’était à l’auteur de « faire court ». Au final, il nous est souvent arrivé de faire de longues notes, exemple : http://www.lesintegristes.net/notes/dart-le-nouveau-langage-de-google/

Une solution pourrait être de ne pas limiter, mais d’afficher un gros avertissement dans l’admin quand la note est trop longue (un compteur de caractères / mots, et si on dépasse, une bordure rouge autour du textarea ou autre).

Questions :
- Est-ce qu’une note est forcément courte ?
- Si oui, combien de caractères / mots ?
### URL associée (proposition)

Faut-il prévoir un champ pour associer, de manière optionnelle, une URL à une note ? Ça permettrait de créer :
- Une note de discussion (on peut toujours mettre des liens dans la note)
- Une note-lien : dans ce cas, le lien est mis en valeur dans la note d’une manière ou d’une autre. On pourrait même récupérer le titre du lien pour créer le titre de la note. Le texte de la note est en rapport direct avec ce lien, et on ne peut en mettre qu’un seul.

**Comment by ericlebihan** [comment]
Pour ton exemple de note longue je préconiserais le format article...

Contenu limité, je suis plutôt pour. ça oblige l'auteur à faire concis.  C'est une pratique très répandue dans la presse écrite (ok on n'est pas journalistes...). On pourrait mettre en place la même alerte que pour les commentaires.

Pour la partie discussion, ne pourrait-on pas innover et avoir une nouvelle rubrique "Ouvrir une discussion" qui serait lancé sous la forme d'une question ? ce qui permettrait de rendre le blog plus vivant qu'il ne l'est aujourd'hui et d'amener plus de trafic. En intro, on explique le principe.

Autrement à la place de note on pourrait utiliser "brève" (http://fr.wikipedia.org/wiki/Br%C3%A8ve_%28information%29) ou quelque chose comme "en bref" pour bien signifier que c'est de l'immédiat, de l'impulsif, de la réaction à chaud,  l'anti-article en somme.

**Comment by bpierre** [comment]
> Pour ton exemple de note longue je préconiserais le format article...

Oui, c’est exactement ce que je voulais souligner : j’ai abusé du format Note ici :-)

> On pourrait mettre en place la même alerte que pour les commentaires.

Oui c’est ce que je vois, ne pas limiter en dur, mais se donner une limite précise à ne pas dépasser. Après si on veut dépasser de quelques mots, ce n’est pas très grave, mais ça donne une indication.

> Ne pourrait-on pas innover et avoir une nouvelle rubrique "Ouvrir une discussion" qui serait lancé sous la forme d'une question.

Pourquoi pas oui, ça pourrait être intéressant.

> Autrement à la place de note on pourrait utiliser "brève".

Oui pourquoi pas, c’est peut-être plus clair que Note.

Et qu’est-ce que tu penses de la Note/Brève-lien ?

On aurait des Notes normales :

```
bla bla bla
bla bla bla
bla bla bla
```

Et des Notes associées à un lien, avec une mise en avant du lien :

```
=========================================================
| Apple issues A Letter to Our Customers Regarding Maps |
| http://www.apple.com/letter-from-tim-cook-on-maps/    |
=========================================================
bla bla bla
bla bla bla
bla bla bla
```

Mais du coup, si on a deux variantes de notes (avec et sans lien), pourquoi pas trois (sans lien, avec lien, question ouverte) ?

Tu verrais quoi comme question par exemple ?

**Comment by ericlebihan** [comment]
Dans ta brève-lien/note-lien, tu aurais donc un lien en chapeau que tu commenterais ?

Je pense que la discussion devrait être distincte des brèves/notes, parce que ce serait vraiment un autre format, beaucoup plus réactif, une demande explicite à réaction au contraire des notes et articles aujourd'hui qui ne sont pas forcément commentées ou très peu commentées dans certains cas.

**Comment by bpierre** [comment]
> Dans ta brève-lien/note-lien, tu aurais donc un lien en chapeau que tu commenterais ?

Oui, Grégoire verra comment mettre le lien en avant, mais la note est un commentaire du lien.

> Je pense que la discussion devrait être distincte des brèves/notes, parce que ce serait vraiment un autre format

OK je vois, d’accord avec toi, il vaut mieux séparer.

**Comment by bpierre** [comment]
J’ai mis tout ça dans la page redesign, n’hésite pas à compléter : https://github.com/lesintegristes/lesintegristes-theme/wiki/%5BFR%5D-Redesign
