### ISSUE TITLE
[FR] Doublon dans le titre des pages d'archives articles et notes

### ISSUE THREAD

**Issue by bluety** [lesintegristes/lesintegristes-theme#40]
Le terme "Les intégristes" est présent deux fois dans la balise `title` des pages d'archives des articles et des notes.
http://www.lesintegristes.net/articles/page/2/ (Articles   (page 2) · Les intégristes Les intégristes)
http://www.lesintegristes.net/notes/page/3/ (Notes   (page 3) · Les intégristes Les intégristes)

**Comment by welovewebdesign** [comment]
My bad, c'est corrigé !

@bpierre j'ai supprimé la branche trop tôt sur ce coup là :/
Du coup j'ai fait la modif en éditant le code directement sur GitHub, pas top j'imagine.
Je maîtrise pas encore ...

**Comment by kaneel** [comment]
github is evil.

Le 7 octobre 2012 15:07, Rémi Couturier notifications@github.com a écrit :

> My bad, c'est corrigé !
> 
> @bpierre https://github.com/bpierre j'ai supprimé la branche trop tôt
> sur ce coup là :/
> Du coup j'ai fait la modif en éditant le code directement sur GitHub, pas
> top j'imagine.
> Je maîtrise pas encore ...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lesintegristes/lesintegristes-theme/issues/40#issuecomment-9207815.

## 

// Guillaume *kaneel *Richard http://mynameiskaneel.com
// With many lower than 3

**Comment by bpierre** [comment]
>  Du coup j'ai fait la modif en éditant le code directement sur GitHub, pas top j'imagine.

Tu as appuyé sur l’un des deux boutons interdits ! :D

![GitHub](http://found.pierrebertet.net/github.png)

Le problème de modifier directement sur GitHub, c’est qu’on ne peut pas tester (une erreur de syntaxe et on casse la prod), et qu’on ne peut modifier qu’un fichier à la fois. Mais bon, ça peut être pratique en cas d’extrême urgence :-)

Par contre aucun problème pour faire des modifs directement dans `master`, mais il vaut mieux le faire en local : `git checkout master`, `git commit`, `git push origin master`.

**Comment by welovewebdesign** [comment]
J'ai juste suivi les conseils d'@ericlebihan :trollface:
