### ISSUE TITLE
What is the "No direct file load" code line purpose?

### ISSUE THREAD

**Issue by welovewebdesign** [lesintegristes/lesintegristes-theme#48]
I'd never seen this line of code in a WordPress theme before. Is it a specific lesintegristes-theme's requirement?

``` php
if (!empty($_SERVER['SCRIPT_FILENAME']) && realpath($_SERVER['SCRIPT_FILENAME']) === realpath(__FILE__)) { die(); }
```

**Comment by bpierre** [comment]
It is for preventing direct access to the files.
The web server should prevent direct access to the theme files (.htaccess), but this is an additionnal mesure.

``` php
// The PHP file called by the server
// (with WordPress, everything is managed by the index.php file)
echo $_SERVER['SCRIPT_FILENAME'];
// The current file
echo __FILE__;

// If both names are the same, it means the current file has been directly called.
```

Example:
http://www.lesintegristes.net/wp-content/themes/lesintegristes/sidebar.php
http://www.presse-citron.net/wordpress_prod/wp-content/themes/steaw-citron/sidebar.php

**Comment by bpierre** [comment]
We should replace it with:

``` php
if (!defined('WP_USE_THEMES')) return;
```

Since the `WP_USE_THEMES` constant is defined in the [index.php](http://core.svn.wordpress.org/trunk/index.php) file.
